### ISSUE TITLE
where is the example folder for the openshift located under kustomize/openshift. 

### ISSUE THREAD

**Issue by condescendent** [CrunchyData/postgres-operator-examples#227]
just want to find an example of openshift deployment. based on the "getting started" document, there is a folder named kustomize/opensihft but i could not find it. Was it deleted?

thanks.

**Comment by benjaminjb** [comment]
Hi @condescendent, our docs may at once point have referred to a kustomize/openshift folder, but that has since been deleted since a cluster defined for openshift is nearly identical to a cluster defined for other platforms. But we have tried to capture the changes required for openshift in our docs and in the CRD itself.

For instance, there is an `openshift` field on the `spec` which can affect certain settings for the cluster: https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster#postgresclusterspec . (However, the operator will attempt to auto-discover if it is deployed to an openshift cluster, so in most cases you shouldn't need to set that.)

(I think our biggest differences when installing to openshift are in the monitoring stack, which we discuss here: https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/day-two/monitoring#configuration .)

I'm going to close this issue, but if you are still having trouble deploying to openshift, feel free to reopen or reach out to us in our [Discord server](https://discord.com/invite/a7vWKG8Ec9).
