### ISSUE TITLE
can i install this operator on a CRC test cluster on my apple M1 laptop?

### ISSUE THREAD

**Issue by condescendent** [CrunchyData/postgres-operator-examples#229]
I am trying to test this operator on my local macpro M1 laptop. I have installed openshift local cluster successfully on my laptop, but when i tried to installed the operator, it looks like the operator has not been created. Is that because my platform is ARM based M1 CPU?

➜  postgres-operator-examples git:(main) ✗ kubectl apply --server-side -k kustomize/install/default
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
customresourcedefinition.apiextensions.k8s.io/pgupgrades.postgres-operator.crunchydata.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/postgresclusters.postgres-operator.crunchydata.com serverside-applied
serviceaccount/pgo serverside-applied
clusterrole.rbac.authorization.k8s.io/postgres-operator serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/postgres-operator serverside-applied
deployment.apps/pgo serverside-applied
➜  postgres-operator-examples git:(main) ✗ kubectl -n postgres-operator get pods \
  --selector=postgres-operator.crunchydata.com/control-plane=postgres-operator \
  --field-selector=status.phase=Running

No resources found in postgres-operator namespace.
➜  postgres-operator-examples git:(main) ✗ kubectl apply -k kustomize/postgres
Error from server (BadRequest): error when creating "kustomize/postgres": PostgresCluster in version "v1beta1" cannot be handled as a PostgresCluster: strict decoding error: unknown field "spec.backups.pgbackrest.repos[0].volume.volumeClaimSpec.volumeMode:", unknown field "spec.instances[0].dataVolumeClaimSpec.volumeMode:"
➜  postgres-operator-examples git:(main) ✗

Please kindly help me, grest apprecaite your help.

**Comment by andrewlecuyer** [comment]
Hi @condescendent, are you still running into trouble with your install?

The latest versions of Crunchy Postgres for Kubernetes (as made available via the Crunchy Developer portal) include containers for both ARM and AMD architectures, so that shouldn't be an issue.

And as for the warnings you are getting when running `kubectl apply`, it appears as though your version of `kubectl` (and more specifically the version of `kustomize` included within that version of `kubectl`) is out of date.  I therefore recommend ensuring your client (which would be `oc` if using OpenShift) is up-to-date.

Hope this helps, and look forward to hearing back if you are still having trouble.

**Comment by benjaminjb** [comment]
Hi @condescendent, I hope the above comment was helpful and that you got it running. I will add that, if you're using an older `kubectl` (or `oc`), you can always download a more recent kustomize and use that to assemble the YAML which you can then send to your kube cluster: https://access.crunchydata.com/documentation/postgres-operator/latest/installation/kustomize#install-the-custom-resource-definition-using-older-kubectl

I'm going to close this issue now, but if you're still experiencing an issue, please feel free to reopen it and continue the conversation.
