### ISSUE TITLE
Location of postgrescluster helm chart in OCI registry?

### ISSUE THREAD

**Issue by sarg3nt** [CrunchyData/postgres-operator-examples#260]
Hi.  Your docs say where the `pgo` chart is in the OCI registry:
  `oci://registry.developers.crunchydata.com/crunchydata/pgo`

But not where the [postgrescluster](https://github.com/CrunchyData/postgres-operator-examples/tree/main/helm/postgres) chart is located.  
I've tried `oci://registry.developers.crunchydata.com/crunchydata/postgrescluster` and a bunch of other guesses, but that's not it and unfortunately it looks like `helm` does not support searching an OCI registry.

Can someone please let me know where the Helm chart is located in the OCI registry?
Thanks!!

**Comment by benjaminjb** [comment]
Hi, @sarg3nt, thanks for bringing this up. Currently, the Helm chart for the postgrescluster is not available via OCI; but we've gotten some feedback about that, so we've got this in our backlog.

(Speaking of feedback, I'm gong to close this ticket because there's some more discussion on this topic here: https://github.com/CrunchyData/postgres-operator/issues/3910 )
