### ISSUE TITLE
Invalid XML error message

### ISSUE THREAD

**Issue by dimitrigraf** [CrunchyData/postgres-operator-examples#29]
Hi there!

I was going through your tutorial, which is very well done btw, and ran into some issues when trying out the S3 backup (Non-AWS). The connection works and stuff arrives in the bucket, but I have errors in the operator logs and when using `kubectl describe postgrescluster <NAME> `.

From `kubectl describe`:

```
Warning  UnableToCreateStanzas  2m50s (x54 over 12m)  postgrescluster-controller  command terminated with exit code 29: ERROR: [029]: invalid xml
```

The operator logs say:
```
time="2021-09-29T14:38:52Z" level=debug msg=Warning file="sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/recorder/recorder.go:98" func="recorder.(*Provider).getBroadcaster.func1.1" message="command terminated with exit code 29: ERROR: [029]: invalid xml\n" object="{PostgresCluster postgres-operator hippo-s3 cbe2bd5a-e4f2-4240-b4f0-7314d1aac1bb postgres-operator.crunchydata.com/v1beta1 82678 }" reason=UnableToCreateStanzas version=5.0.2-0
```

I realized later that version 5.0.2, which is used by default, is not yet publicly released. But this might help us both in the long term, anyway. 

If you need more info I'll be happy to help.

**Comment by jkatz** [comment]
Thanks for the kind words on the tutorial. A few things:

1. 5.0.2 is both [open source](https://github.com/CrunchyData/postgres-operator) and [publicly released](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x).
1. The "invalid XML" error is coming from your S3-like system. I would recommend checking the logs there to see what is incorrect. This is likely due to configuration.
1. This is the repository for the examples. Bugs/enhancements requests should be opened in https://github.com/CrunchyData/postgres-operator. There is guidance on [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) as well.

Thanks!

**Comment by dimitrigraf** [comment]
Thanks for your quick answer and the hints. I'll check the logs on the S3 side and report issues in the proper repo in the future. 

Regarding the release: I'm a bit confused here because the latest pre-release in the github operator repo is 4.7.3. What am I missing?

**Comment by dimitrigraf** [comment]
@jkatz 

Alright, I found the answer to my release/version question: `Where are the release tags for PGO v5?` in the [FAQ](https://access.crunchydata.com/documentation/postgres-operator/v5/faq/)

And I found the problem behind the `invalid XML` error messages: I specified my endpoint together with the port (`url-without-https:port`). That seems to have cause the mentioned error messages. Maybe that's something you want to document and hint at in the logs. For example, when specifying the endpoint with `https://endpoint-url` the operator logs specifically say `ERROR: [031]: 'https://s3-eu-central-1.sds.dectris.io' is not valid for option 'repo1-s3-endpoint'\n       HINT: port is not a positive integer.\n"`

The `positive integer` part is actually quite interesting since it could lead you to specifying the port which then in return leads to the `invalid XML` error. Maybe that's sth  you want to look into.
